M48
; DRILL file {KiCad (6.0.11)} date Fri Mar 31 15:13:40 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-31T15:13:40+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X4.0748Y-1.8701
X4.0748Y-3.7992
X6.3583Y-1.8701
X6.3583Y-3.7992
T0
M30
